---
# Source: https://github.com/projectcalico/calico/blob/v3.30.3/charts/calico/templates/calico-node.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-cni-plugin
  namespace: kube-system
